# Generated by Django 5.2.4 on 2026-01-20 07:10

import django.db.models.deletion
import uuid6
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FamilyMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(blank=True, max_length=150)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=10)),
                ('is_married', models.BooleanField(default=False)),
                ('married_date', models.DateField(blank=True, null=True)),
                ('is_person_alive', models.BooleanField(default=True)),
                ('email_address', models.EmailField(max_length=254, unique=True)),
                ('profession', models.CharField(blank=True, max_length=255, null=True)),
                ('relation_type', models.CharField(blank=True, choices=[('father', 'Father'), ('mother', 'Mother'), ('siblings', 'Siblings'), ('spouse', 'Spouse'), ('child', 'Child')], max_length=51)),
                ('death_date', models.DateField(blank=True, null=True)),
                ('birth_date', models.DateField()),
                ('profile_image_s3_key', models.CharField(blank=True, max_length=512, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_family_members', to=settings.AUTH_USER_MODEL)),
                ('primary_father', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='family_tree.familymember')),
                ('primary_mother', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='family_tree.familymember')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FamilyTree',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid6.uuid7, editable=False, primary_key=True, serialize=False)),
                ('slug', models.SlugField(blank=True, max_length=255, null=True, unique=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='family_trees', to=settings.AUTH_USER_MODEL)),
                ('root_member', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='root_of_tree', to='family_tree.familymember')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='familymember',
            name='family_tree',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='family_tree.familytree'),
        ),
        migrations.CreateModel(
            name='ParentalRelationship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parent_type', models.CharField(choices=[('biological', 'Biological'), ('adopted', 'Adopted'), ('step', 'Step')], default='biological', max_length=20)),
                ('is_deleted', models.BooleanField(default=False)),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parents', to='family_tree.familymember')),
                ('family_tree', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parental_relationships', to='family_tree.familytree')),
                ('father', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children_as_father', to='family_tree.familymember')),
                ('mother', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children_as_mother', to='family_tree.familymember')),
            ],
        ),
        migrations.CreateModel(
            name='Partnership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('marriage_date', models.DateTimeField(blank=True, null=True)),
                ('divorce_date', models.DateTimeField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('partner_generation_no', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('family_tree', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partnerships', to='family_tree.familytree')),
                ('husband', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='partnerships_as_husband', to='family_tree.familymember')),
                ('wife', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='partnerships_as_wife', to='family_tree.familymember')),
            ],
            options={
                'unique_together': {('husband', 'wife')},
            },
        ),
    ]
