# Generated by Django 5.2.4 on 2026-01-20 09:14

import ckeditor_uploader.fields
import django.db.models.deletion
import uuid6
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('family_tree', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FamilyTreeDiaryCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('color_code', models.CharField(max_length=20)),
                ('slug', models.SlugField(unique=True)),
                ('is_deleted', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'family_tree_diary_category',
            },
        ),
        migrations.CreateModel(
            name='FamilyTreeDiary',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid6.uuid7, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', ckeditor_uploader.fields.RichTextUploadingField()),
                ('is_deleted', models.BooleanField(default=False)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='family_tree_diaries', to=settings.AUTH_USER_MODEL)),
                ('family_tree', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diaries', to='family_tree.familytree')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='diaries', to='family_tree.familytreediarycategory')),
            ],
            options={
                'db_table': 'family_tree_diary',
                'ordering': ['-created_at'],
            },
        ),
    ]
