# Generated by Django 5.2.4 on 2026-01-13 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('family_tree', '0002_familytree_root_member'),
    ]

    operations = [
        migrations.AlterField(
            model_name='familymember',
            name='profession',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
