# Generated by Django 5.2.4 on 2026-01-21 06:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('family_tree', '0002_familytreediarycategory_familytreediary'),
    ]

    operations = [
        migrations.CreateModel(
            name='FamilyTreeRecipient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('recipient_email', models.EmailField(max_length=254)),
                ('permissions', models.CharField(choices=[('view', 'View'), ('edit', 'Edit')], default='view', max_length=100)),
                ('is_deleted', models.BooleanField(default=False)),
                ('family_tree', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='family_tree_recipients', to='family_tree.familytree')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
