# Generated by Django 5.2.4 on 2026-01-21 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('family_tree', '0003_familytreerecipient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='familymember',
            name='email_address',
            field=models.EmailField(max_length=254),
        ),
    ]
