# Generated by Django 5.2.4 on 2026-01-14 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('family_tree', '0003_alter_familymember_profession'),
    ]

    operations = [
        migrations.AddField(
            model_name='familymember',
            name='member_role',
            field=models.CharField(blank=True, max_length=51, null=True),
        ),
    ]
