# Generated by Django 5.2.4 on 2026-01-14 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('family_tree', '0004_familymember_member_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='familymember',
            name='member_role',
        ),
    ]
