# Generated by Django 5.2.4 on 2026-03-02 09:24

import django.db.models.deletion
import uuid6
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('family_tree', '0005_familytreegallery'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='familymember',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='member_image/'),
        ),
        migrations.CreateModel(
            name='UploadSession',
            fields=[
                ('id', models.UUIDField(default=uuid6.uuid7, editable=False, primary_key=True, serialize=False)),
                ('target_type', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('Initialized', 'Initialized'), ('Pending', 'Pending'), ('Uploading', 'Uploading'), ('Completed', 'Completed'), ('Aborted', 'Aborted')], max_length=30)),
                ('family_tree', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='family_tree.familytree')),
                ('member', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='family_tree.familymember')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
