# Generated by Django 5.2.4 on 2026-01-15 07:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('family_tree', '0005_remove_familymember_member_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='familymember',
            name='primary_father',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='family_tree.familymember'),
        ),
        migrations.AddField(
            model_name='familymember',
            name='primary_mother',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='family_tree.familymember'),
        ),
    ]
