# Generated by Django 5.2.4 on 2026-03-09 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('family_tree', '0006_familymember_profile_image_uploadsession'),
    ]

    operations = [
        migrations.AlterField(
            model_name='familymember',
            name='email_address',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
