# Generated by Django 5.2.4 on 2026-01-15 08:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('family_tree', '0006_familymember_primary_father_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partnership',
            name='husband',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='partnerships_as_husband', to='family_tree.familymember'),
        ),
        migrations.AlterField(
            model_name='partnership',
            name='wife',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='partnerships_as_wife', to='family_tree.familymember'),
        ),
    ]
