# Generated by Django 5.2.4 on 2026-03-23 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('family_tree', '0007_alter_familymember_email_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='familymember',
            name='sibling_group_id',
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
