# Generated by Django 5.2.4 on 2026-01-16 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('family_tree', '0007_alter_partnership_husband_alter_partnership_wife'),
    ]

    operations = [
        migrations.AddField(
            model_name='partnership',
            name='partner_generation_no',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
