# Generated by Django 5.2.4 on 2026-01-19 05:54

import uuid6
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('family_tree', '0008_partnership_partner_generation_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='familytree',
            name='id',
            field=models.UUIDField(default=uuid6.uuid7, editable=False, primary_key=True, serialize=False),
        ),
    ]
