# Generated by Django 5.2.4 on 2026-04-20 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memory_map', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='memorymediadetails',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='memory_map/thumbnails/'),
        ),
    ]
