# Generated by Django 5.2.4 on 2026-04-24 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memory_map', '0002_memorymediadetails_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='memorymapbucketinfo',
            name='tagged_friends',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
