# Generated by Django 5.2.4 on 2025-08-07 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomMemoryRoomTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Is Deleted')),
                ('name', models.CharField(max_length=255, verbose_name='Memory Room Name')),
                ('slug', models.SlugField(blank=True, null=True, verbose_name='Slug')),
                ('summary', models.TextField(blank=True, null=True, verbose_name='Memory Room Summary')),
            ],
            options={
                'verbose_name': 'Custom Memory Room Template',
                'verbose_name_plural': 'Custom Memory Room Templates',
            },
        ),
        migrations.CreateModel(
            name='CustomTimeCapSoulTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Is Deleted')),
                ('name', models.CharField(max_length=255, verbose_name='TimeCapSoul Name')),
                ('slug', models.SlugField(verbose_name='Slug')),
                ('summary', models.TextField(blank=True, null=True, verbose_name='TimeCapSoul Summary')),
            ],
            options={
                'verbose_name': 'Custom TimeCapSoul Template',
                'verbose_name_plural': 'Custom TimeCapSoul Templates',
            },
        ),
        migrations.CreateModel(
            name='MemoryRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Is Deleted')),
            ],
            options={
                'verbose_name': 'Memory Room',
                'verbose_name_plural': 'Memory Rooms',
            },
        ),
        migrations.CreateModel(
            name='MemoryRoomDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Is Deleted')),
                ('occupied_storage', models.CharField(blank=True, help_text='Storage used timecap-soul', max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'Memory Room Detail',
                'verbose_name_plural': 'Memory Room Details',
            },
        ),
        migrations.CreateModel(
            name='MemoryRoomMediaFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Is Deleted')),
                ('file', models.FileField(upload_to='memory_room_files/', verbose_name='Media File')),
                ('file_type', models.CharField(choices=[('image', 'Image'), ('video', 'Video'), ('audio', 'Audio'), ('other', 'Other')], default='other', max_length=20, verbose_name='File Type')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('is_cover_image', models.BooleanField(default=False, verbose_name='Use as Cover')),
                ('thumbnail_url', models.URLField(blank=True, null=True)),
                ('thumbnail_key', models.CharField(blank=True, max_length=255, null=True)),
                ('file_size', models.BigIntegerField(blank=True, null=True, verbose_name='File size')),
                ('s3_url', models.URLField(blank=True, null=True)),
                ('s3_key', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'Memory Room Media File',
                'verbose_name_plural': 'Memory Room Media Files',
            },
        ),
        migrations.CreateModel(
            name='MemoryRoomTemplateDefault',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Is Deleted')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('summary', models.TextField(blank=True, null=True, verbose_name='Summary')),
                ('slug', models.SlugField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Default Memory Room Template',
                'verbose_name_plural': 'Default Memory Room Templates',
            },
        ),
        migrations.CreateModel(
            name='RecipientsDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Is Deleted')),
            ],
            options={
                'verbose_name': 'Recipient Detail',
                'verbose_name_plural': 'Recipient Details',
            },
        ),
        migrations.CreateModel(
            name='TimeCapSoul',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Is Deleted')),
                ('status', models.CharField(choices=[('sealed', 'Sealed With Love'), ('unlocked', 'Unlocked'), ('created', 'Being Crafted')], default='created', max_length=255)),
            ],
            options={
                'verbose_name': 'TimeCapSoul',
                'verbose_name_plural': 'TimeCapSouls',
            },
        ),
        migrations.CreateModel(
            name='TimeCapSoulDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Is Deleted')),
                ('is_locked', models.BooleanField(default=False)),
                ('unlock_date', models.DateTimeField(blank=True, null=True, verbose_name='Unlock Date')),
                ('occupied_storage', models.CharField(blank=True, help_text='Storage used timecap-soul', max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'TimeCapSoul Detail',
                'verbose_name_plural': 'TimeCapSoul Details',
            },
        ),
        migrations.CreateModel(
            name='TimeCapSoulMediaFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Is Deleted')),
                ('file', models.FileField(upload_to='media_files/', verbose_name='Media File')),
                ('file_type', models.CharField(choices=[('image', 'Image'), ('video', 'Video'), ('audio', 'Audio'), ('other', 'Other')], default='other', max_length=20, verbose_name='File Type')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('file_size', models.BigIntegerField(blank=True, null=True, verbose_name='File Size')),
                ('s3_url', models.URLField(blank=True, null=True, verbose_name='S3 URL')),
                ('s3_key', models.CharField(blank=True, max_length=255, null=True, verbose_name='S3 Key')),
                ('is_cover_image', models.BooleanField(default=False, help_text='Mark if this media is the cover image')),
            ],
            options={
                'verbose_name': 'TimeCapSoul Media File',
                'verbose_name_plural': 'TimeCapSoul Media Files',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TimeCapSoulMediaFileReplica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Is Deleted')),
                ('file', models.FileField(upload_to='media_files/', verbose_name='Media File')),
                ('file_type', models.CharField(choices=[('image', 'Image'), ('video', 'Video'), ('audio', 'Audio'), ('other', 'Other')], default='other', max_length=20, verbose_name='File Type')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('file_size', models.BigIntegerField(blank=True, null=True, verbose_name='File Size')),
                ('s3_url', models.URLField(blank=True, null=True, verbose_name='S3 URL')),
                ('s3_key', models.CharField(blank=True, max_length=255, null=True, verbose_name='S3 Key')),
                ('is_cover_image', models.BooleanField(default=False, help_text='Mark if this media is the cover image')),
            ],
            options={
                'verbose_name': 'TimeCapSoul Media File Replica',
                'verbose_name_plural': 'TimeCapSoul Media File Replicas',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TimeCapSoulRecipient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Is Deleted')),
                ('name', models.CharField(max_length=255, verbose_name='Recipient Name')),
                ('email', models.EmailField(max_length=254, verbose_name='Recipient Email')),
            ],
            options={
                'verbose_name': 'TimeCapSoul Recipient',
                'verbose_name_plural': 'TimeCapSoul Recipients',
            },
        ),
        migrations.CreateModel(
            name='TimeCapSoulReplica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Is Deleted')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='TimeCapSoul Name')),
                ('slug', models.SlugField(blank=True, null=True, verbose_name='Slug')),
                ('summary', models.TextField(blank=True, null=True, verbose_name='TimeCapSoul Summary')),
                ('status', models.CharField(blank=True, choices=[('sealed', 'Sealed With Love'), ('unlocked', 'Unlocked'), ('created', 'Being Crafted')], max_length=255, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TimeCapSoulTemplateDefault',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Is Deleted')),
                ('name', models.CharField(max_length=255, verbose_name='TimeCapSoul Name')),
                ('summary', models.TextField(blank=True, max_length=255, null=True, verbose_name='TimeCapSoul Summary')),
                ('slug', models.SlugField(blank=True, null=True, verbose_name='Slug')),
            ],
            options={
                'verbose_name': 'Default TimeCapSoul Template',
                'verbose_name_plural': 'Default TimeCapSoul Templates',
            },
        ),
        migrations.CreateModel(
            name='UserMapper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Is Deleted')),
                ('max_storage_limit', models.CharField(max_length=100, verbose_name='Max Storage Limit')),
                ('current_storage', models.CharField(max_length=100, verbose_name='Current Storage')),
            ],
            options={
                'verbose_name': 'User Mapper',
                'verbose_name_plural': 'User Mappers',
            },
        ),
    ]
