# Generated by Django 5.2.4 on 2025-07-11 06:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('userauth', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeCapSoulRecipient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_created', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Is Deleted')),
                ('name', models.CharField(max_length=255, verbose_name='Recipient Name')),
                ('email', models.EmailField(max_length=254, verbose_name='Recipient Email')),
            ],
            options={
                'verbose_name': 'TimeCapSoul Recipient',
                'verbose_name_plural': 'TimeCapSoul Recipients',
            },
        ),
        migrations.CreateModel(
            name='CustomMemoryRoomTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_created', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Is Deleted')),
                ('name', models.CharField(max_length=255, verbose_name='Template Name')),
                ('slug', models.SlugField(blank=True, null=True, verbose_name='Slug')),
                ('summary', models.TextField(blank=True, null=True, verbose_name='Template Summary')),
                ('cover_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='custom_memory_room_template_covers', to='userauth.assets', verbose_name='Cover Image')),
            ],
            options={
                'verbose_name': 'Custom Memory Room Template',
                'verbose_name_plural': 'Custom Memory Room Templates',
            },
        ),
        migrations.CreateModel(
            name='CustomTimeCapSoulTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_created', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Is Deleted')),
                ('name', models.CharField(max_length=255, verbose_name='Template Name')),
                ('slug', models.SlugField(verbose_name='Slug')),
                ('summary', models.TextField(blank=True, null=True, verbose_name='Template Summary')),
                ('cover_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='custom_timecapsoul_template_covers', to='userauth.assets', verbose_name='Cover Image')),
            ],
            options={
                'verbose_name': 'Custom TimeCapSoul Template',
                'verbose_name_plural': 'Custom TimeCapSoul Templates',
            },
        ),
        migrations.CreateModel(
            name='MemoryRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_created', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Is Deleted')),
                ('room_template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='memory_rooms', to='memory_room.custommemoryroomtemplate', verbose_name='Room Template')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memory_rooms', to=settings.AUTH_USER_MODEL, verbose_name='Owner')),
            ],
            options={
                'verbose_name': 'Memory Room',
                'verbose_name_plural': 'Memory Rooms',
            },
        ),
        migrations.CreateModel(
            name='MemoryRoomMediaFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_created', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Is Deleted')),
                ('file', models.FileField(upload_to='memory_room_files/', verbose_name='Media File')),
                ('types', models.CharField(choices=[('image', 'Image'), ('pdf', 'PDF'), ('video', 'Video'), ('audio', 'Audio'), ('document', 'Document'), ('archive', 'Archive'), ('code', 'Code File'), ('art', 'Art & Scans'), ('other', 'Other')], default='other', max_length=20, verbose_name='File Type')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('is_cover_image', models.BooleanField(default=False, verbose_name='Use as Cover')),
                ('file_size', models.BigIntegerField(blank=True, null=True, verbose_name='File size')),
                ('cover_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='memory_room_media_cover', to='userauth.assets', verbose_name='Cover Image')),
            ],
            options={
                'verbose_name': 'Memory Room Media File',
                'verbose_name_plural': 'Memory Room Media Files',
            },
        ),
        migrations.CreateModel(
            name='MemoryRoomDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_created', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Is Deleted')),
                ('memory_room', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='memory_room.memoryroom', verbose_name='Memory Room')),
                ('media_files', models.ManyToManyField(blank=True, related_name='memory_room_details', to='memory_room.memoryroommediafile', verbose_name='Media Files')),
            ],
            options={
                'verbose_name': 'Memory Room Detail',
                'verbose_name_plural': 'Memory Room Details',
            },
        ),
        migrations.CreateModel(
            name='MemoryRoomTemplateDefault',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_created', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Is Deleted')),
                ('name', models.CharField(max_length=255, verbose_name='Template Name')),
                ('summary', models.TextField(blank=True, null=True, verbose_name='Template Summary')),
                ('slug', models.SlugField(blank=True, null=True)),
                ('cover_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='memory_room_template_covers', to='userauth.assets', verbose_name='Cover Image')),
            ],
            options={
                'verbose_name': 'Default Memory Room Template',
                'verbose_name_plural': 'Default Memory Room Templates',
            },
        ),
        migrations.AddField(
            model_name='custommemoryroomtemplate',
            name='default_template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='custom_templates', to='memory_room.memoryroomtemplatedefault', verbose_name='Default Template'),
        ),
        migrations.CreateModel(
            name='TimeCapSoul',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_created', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Is Deleted')),
                ('capsoul_template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='timecapsouls', to='memory_room.customtimecapsoultemplate', verbose_name='CapSoul Template')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timecapsouls', to=settings.AUTH_USER_MODEL, verbose_name='Owner')),
            ],
            options={
                'verbose_name': 'TimeCapSoul',
                'verbose_name_plural': 'TimeCapSouls',
            },
        ),
        migrations.CreateModel(
            name='TimeCapSoulMediaFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_created', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Is Deleted')),
                ('file', models.FileField(upload_to='time_capsoul_media_file/', verbose_name='Media File')),
                ('types', models.CharField(choices=[('image', 'Image'), ('pdf', 'PDF'), ('video', 'Video'), ('audio', 'Audio'), ('document', 'Document'), ('archive', 'Archive'), ('code', 'Code File'), ('art', 'Art & Scans'), ('other', 'Other')], default='other', max_length=20, verbose_name='File Type')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('is_cover_image', models.BooleanField(default=False, verbose_name='Use as Cover')),
                ('file_size', models.BigIntegerField(blank=True, null=True, verbose_name='File size')),
                ('cover_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='time_capsoul_media_cover', to='userauth.assets', verbose_name='Cover Image')),
            ],
            options={
                'verbose_name': 'Time CapSoul Media File',
                'verbose_name_plural': 'Time CapSoul Media File',
            },
        ),
        migrations.CreateModel(
            name='TimeCapSoulDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_created', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Is Deleted')),
                ('unlock_date', models.DateTimeField(verbose_name='Unlock Date')),
                ('time_capsoul', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='memory_room.timecapsoul', verbose_name='TimeCapSoul')),
                ('media_files', models.ManyToManyField(blank=True, related_name='timecapsoul_details', to='memory_room.timecapsoulmediafile', verbose_name='Media Files')),
            ],
            options={
                'verbose_name': 'TimeCapSoul Detail',
                'verbose_name_plural': 'TimeCapSoul Details',
            },
        ),
        migrations.CreateModel(
            name='RecipientsDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_created', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Is Deleted')),
                ('time_capsoul', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipient_details', to='memory_room.timecapsoul', verbose_name='TimeCapSoul')),
                ('recipients', models.ManyToManyField(blank=True, related_name='recipient_details', to='memory_room.timecapsoulrecipient', verbose_name='Recipients')),
            ],
            options={
                'verbose_name': 'Recipient Detail',
                'verbose_name_plural': 'Recipient Details',
            },
        ),
        migrations.CreateModel(
            name='TimeCapSoulTemplateDefault',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_created', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Is Deleted')),
                ('name', models.CharField(max_length=255, verbose_name='Template Name')),
                ('summary', models.TextField(blank=True, null=True, verbose_name='Template Summary')),
                ('slug', models.SlugField(blank=True, null=True, verbose_name='Slug')),
                ('cover_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='timecapsoul_template_covers', to='userauth.assets', verbose_name='Cover Image')),
            ],
            options={
                'verbose_name': 'Default TimeCapSoul Template',
                'verbose_name_plural': 'Default TimeCapSoul Templates',
            },
        ),
        migrations.AddField(
            model_name='customtimecapsoultemplate',
            name='default_template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='custom_templates', to='memory_room.timecapsoultemplatedefault', verbose_name='Default Template'),
        ),
        migrations.CreateModel(
            name='UserMapper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_created', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Is Deleted')),
                ('max_storage_limit', models.CharField(max_length=100, verbose_name='Max Storage Limit')),
                ('current_storage', models.CharField(max_length=100, verbose_name='Current Storage')),
                ('memory_room', models.ManyToManyField(blank=True, related_name='user_mappers', to='memory_room.memoryroom', verbose_name='Memory Rooms')),
                ('time_capsoul', models.ManyToManyField(blank=True, related_name='user_mappers', to='memory_room.timecapsoul', verbose_name='TimeCapsouls')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_mapper', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'User Mapper',
                'verbose_name_plural': 'User Mappers',
            },
        ),
    ]
