# Generated by Django 5.2.4 on 2025-07-11 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memory_room', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='custommemoryroomtemplate',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Memory Room Name'),
        ),
        migrations.AlterField(
            model_name='custommemoryroomtemplate',
            name='summary',
            field=models.TextField(blank=True, null=True, verbose_name='Memory Room Summary'),
        ),
        migrations.AlterField(
            model_name='customtimecapsoultemplate',
            name='name',
            field=models.CharField(max_length=255, verbose_name='TimeCapSoul Name'),
        ),
        migrations.AlterField(
            model_name='customtimecapsoultemplate',
            name='summary',
            field=models.TextField(blank=True, null=True, verbose_name='TimeCapSoul Summary'),
        ),
        migrations.AlterField(
            model_name='memoryroomtemplatedefault',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='memoryroomtemplatedefault',
            name='summary',
            field=models.TextField(blank=True, null=True, verbose_name='Summary'),
        ),
        migrations.AlterField(
            model_name='timecapsoultemplatedefault',
            name='name',
            field=models.CharField(max_length=255, verbose_name='TimeCapSoul Name'),
        ),
        migrations.AlterField(
            model_name='timecapsoultemplatedefault',
            name='summary',
            field=models.TextField(blank=True, null=True, verbose_name='TimeCapSoul Summary'),
        ),
    ]
