# Generated by Django 5.2.4 on 2025-08-07 06:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('memory_room', '0001_initial'),
        ('userauth', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='custommemoryroomtemplate',
            name='cover_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='custom_memory_room_template_covers', to='userauth.assets', verbose_name='Cover Image'),
        ),
        migrations.AddField(
            model_name='customtimecapsoultemplate',
            name='cover_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='custom_timecapsoul_template_covers', to='userauth.assets', verbose_name='Cover Image'),
        ),
        migrations.AddField(
            model_name='memoryroom',
            name='room_template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='memory_rooms', to='memory_room.custommemoryroomtemplate', verbose_name='Room Template'),
        ),
        migrations.AddField(
            model_name='memoryroom',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memory_rooms', to=settings.AUTH_USER_MODEL, verbose_name='Owner'),
        ),
        migrations.AddField(
            model_name='memoryroomdetail',
            name='memory_room',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='memory_room.memoryroom', verbose_name='Memory Room'),
        ),
        migrations.AddField(
            model_name='memoryroommediafile',
            name='cover_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='memory_room_media_cover', to='userauth.assets', verbose_name='Cover Image'),
        ),
        migrations.AddField(
            model_name='memoryroommediafile',
            name='memory_room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='memory_media_files', to='memory_room.memoryroom'),
        ),
        migrations.AddField(
            model_name='memoryroommediafile',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_media_files', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='memoryroomdetail',
            name='media_files',
            field=models.ManyToManyField(blank=True, related_name='memory_room_details', to='memory_room.memoryroommediafile', verbose_name='Media Files'),
        ),
        migrations.AddField(
            model_name='memoryroomtemplatedefault',
            name='cover_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='memory_room_template_covers', to='userauth.assets', verbose_name='Cover Image'),
        ),
        migrations.AddField(
            model_name='custommemoryroomtemplate',
            name='default_template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='custom_templates', to='memory_room.memoryroomtemplatedefault', verbose_name='Default Template'),
        ),
        migrations.AddField(
            model_name='timecapsoul',
            name='capsoul_template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='timecapsouls', to='memory_room.customtimecapsoultemplate', verbose_name='CapSoul Template'),
        ),
        migrations.AddField(
            model_name='timecapsoul',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timecapsouls', to=settings.AUTH_USER_MODEL, verbose_name='Owner'),
        ),
        migrations.AddField(
            model_name='recipientsdetail',
            name='time_capsoul',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='recipient_details', to='memory_room.timecapsoul', verbose_name='TimeCapSoul'),
        ),
        migrations.AddField(
            model_name='timecapsouldetail',
            name='time_capsoul',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='memory_room.timecapsoul', verbose_name='TimeCapSoul'),
        ),
        migrations.AddField(
            model_name='timecapsoulmediafile',
            name='thumbnail',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='time_capsoul_media_thumbnails', to='userauth.assets', verbose_name='Thumbnail'),
        ),
        migrations.AddField(
            model_name='timecapsoulmediafile',
            name='time_capsoul',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='timecapsoul_media_files', to='memory_room.timecapsoul'),
        ),
        migrations.AddField(
            model_name='timecapsoulmediafile',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='time_capsoul_media_files', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='timecapsouldetail',
            name='media_files',
            field=models.ManyToManyField(blank=True, related_name='timecapsoul_details', to='memory_room.timecapsoulmediafile', verbose_name='Media Files'),
        ),
        migrations.AddField(
            model_name='timecapsoulmediafilereplica',
            name='parent_media_file',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='replica', to='memory_room.timecapsoulmediafile'),
        ),
        migrations.AddField(
            model_name='timecapsoulmediafilereplica',
            name='thumbnail',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='timecapsoul_media_file_replicas_thumbnails', to='userauth.assets', verbose_name='Thumbnail'),
        ),
        migrations.AddField(
            model_name='timecapsoulmediafilereplica',
            name='time_capsoul',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='media_file_replicas', to='memory_room.timecapsoul'),
        ),
        migrations.AddField(
            model_name='timecapsoulmediafilereplica',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='timecapsoul_media_file_replicas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='recipientsdetail',
            name='recipients',
            field=models.ManyToManyField(blank=True, related_name='recipient_details', to='memory_room.timecapsoulrecipient', verbose_name='Recipients'),
        ),
        migrations.AddField(
            model_name='timecapsoulreplica',
            name='cover_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='timecapsoul_replica', to='userauth.assets', verbose_name='Cover Image'),
        ),
        migrations.AddField(
            model_name='timecapsoulreplica',
            name='parent_time_capsoul',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='time_capsoul_replica', to='memory_room.timecapsoul'),
        ),
        migrations.AddField(
            model_name='timecapsoulreplica',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='time_capsoul_replica', to=settings.AUTH_USER_MODEL, verbose_name='Owner'),
        ),
        migrations.AddField(
            model_name='timecapsoultemplatedefault',
            name='cover_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='timecapsoul_template_covers', to='userauth.assets', verbose_name='Cover Image'),
        ),
        migrations.AddField(
            model_name='customtimecapsoultemplate',
            name='default_template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='custom_templates', to='memory_room.timecapsoultemplatedefault', verbose_name='Default Template'),
        ),
        migrations.AddField(
            model_name='usermapper',
            name='memory_room',
            field=models.ManyToManyField(blank=True, related_name='user_mappers', to='memory_room.memoryroom', verbose_name='Memory Rooms'),
        ),
        migrations.AddField(
            model_name='usermapper',
            name='time_capsoul',
            field=models.ManyToManyField(blank=True, related_name='user_mappers', to='memory_room.timecapsoul', verbose_name='TimeCapsouls'),
        ),
        migrations.AddField(
            model_name='usermapper',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_mapper', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
    ]
