# Generated by Django 5.2.4 on 2025-07-14 06:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('memory_room', '0002_alter_custommemoryroomtemplate_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='memoryroommediafile',
            old_name='types',
            new_name='file_type',
        ),
        migrations.RenameField(
            model_name='timecapsoulmediafile',
            old_name='types',
            new_name='file_type',
        ),
    ]
