# Generated by Django 5.2.4 on 2025-07-14 06:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memory_room', '0003_rename_types_memoryroommediafile_file_type_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='memoryroommediafile',
            name='memory_room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='memory_media_files', to='memory_room.memoryroom'),
        ),
        migrations.AddField(
            model_name='memoryroommediafile',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_media_files', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='timecapsoulmediafile',
            name='time_capsoul',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='timecapsoul_media_files', to='memory_room.timecapsoul'),
        ),
        migrations.AddField(
            model_name='timecapsoulmediafile',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_timecapsoul_media_files', to=settings.AUTH_USER_MODEL),
        ),
    ]
