# Generated by Django 5.2.4 on 2025-08-21 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memory_room', '0003_alter_memoryroommediafile_file_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timecapsoulmediafile',
            name='file_size',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='File Size'),
        ),
        migrations.AlterField(
            model_name='timecapsoulmediafilereplica',
            name='file_size',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='File Size'),
        ),
    ]
