# Generated by Django 5.2.4 on 2025-08-26 09:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memory_room', '0004_alter_timecapsoulmediafile_file_size_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='timecapsoulmediafilereplica',
            name='refrence_replica',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='referenced_by_media', to='memory_room.timecapsoulmediafilereplica', verbose_name='Reference Replica'),
        ),
        migrations.AddField(
            model_name='timecapsoulreplica',
            name='refrence_replica',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='referenced_by', to='memory_room.timecapsoulreplica', verbose_name='Reference Replica'),
        ),
        migrations.AlterField(
            model_name='timecapsoulmediafilereplica',
            name='parent_media_file',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replica', to='memory_room.timecapsoulmediafile'),
        ),
        migrations.AlterField(
            model_name='timecapsoulmediafilereplica',
            name='time_capsoul',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='media_file_replicas', to='memory_room.timecapsoulreplica'),
        ),
    ]
