# Generated by Django 5.2.4 on 2025-08-27 19:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memory_room', '0005_timecapsoulmediafilereplica_refrence_replica_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='timecapsoul',
            name='capsoul_replica_refrence',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='referenced_by', to='memory_room.timecapsoul', verbose_name='Reference Replica'),
        ),
        migrations.AddField(
            model_name='timecapsoulmediafile',
            name='media_refrence_replica',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='referenced_by_media', to='memory_room.timecapsoulmediafile', verbose_name='Reference Replica'),
        ),
    ]
