# Generated by Django 5.2.4 on 2025-09-10 07:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memory_room', '0006_timecapsoul_capsoul_replica_refrence_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Is Deleted')),
                ('category', models.CharField(choices=[('capsoul', 'Capsoul'), ('reminder', 'Reminders & Memories'), ('occasion', 'Special Occasions'), ('room', 'Memory Room'), ('security', 'Account & Security')], max_length=50)),
                ('category_type', models.CharField(choices=[('capsoul_sealed', 'Capsoul Sealed'), ('capsoul_invite_received', 'Capsoul Invite Received'), ('capsoul_almost_unlock', 'Capsoul Almost Unlock'), ('capsoul_unlocked', 'Capsoul Unlocked'), ('capsoul_waiting', 'Capsoul Waiting'), ('capsoul_reminder_7_days', 'Capsoul Reminder (7 Days)'), ('memory_preservation', 'Memory Preservation Reminder'), ('memory_one_year_ago', 'Memory From One Year Ago'), ('anniversary_reminder', 'Anniversary Reminder'), ('birthday_reminder', 'Birthday Reminder'), ('festival_greeting', 'Festival Greeting'), ('room_no_media', 'Room Has No Media'), ('password_updated', 'Password Updated'), ('new_login_detected', 'New Login Detected'), ('profile_updated', 'Profile Updated')], max_length=50)),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('memory_room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='memory_room.memoryroom')),
                ('time_capsoul', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='memory_room.timecapsoul')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
