# Generated by Django 5.2.4 on 2025-07-21 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memory_room', '0007_rename_is_created_custommemoryroomtemplate_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='memoryroommediafile',
            name='thumbnail_key',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='memoryroommediafile',
            name='thumbnail_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='timecapsoulmediafile',
            name='thumbnail_key',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='timecapsoulmediafile',
            name='thumbnail_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
