# Generated by Django 5.2.4 on 2025-09-11 07:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memory_room', '0007_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='timecapsoulrecipient',
            name='is_logged_in',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='timecapsoulrecipient',
            name='is_opened',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='timecapsoulrecipient',
            name='time_capsoul',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recipient_detail', to='memory_room.timecapsoul', verbose_name='TimeCapSoul'),
        ),
    ]
