# Generated by Django 5.2.4 on 2025-07-24 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memory_room', '0008_memoryroommediafile_thumbnail_key_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timecapsouldetail',
            name='unlock_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Unlock Date'),
        ),
    ]
