# Generated by Django 5.2.4 on 2025-09-15 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memory_room', '0008_timecapsoulrecipient_is_logged_in_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='timecapsoulrecipient',
            constraint=models.UniqueConstraint(fields=('time_capsoul', 'email'), name='unique_capsoul_email'),
        ),
    ]
