# Generated by Django 5.2.4 on 2025-09-17 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memory_room', '0009_timecapsoulrecipient_unique_capsoul_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='timecapsoulrecipient',
            name='is_capsoul_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
