# Generated by Django 5.2.4 on 2025-07-28 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memory_room', '0009_alter_timecapsouldetail_unlock_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timecapsoulmediafile',
            name='cover_image',
        ),
        migrations.AddField(
            model_name='timecapsoulmediafile',
            name='title',
            field=models.CharField(blank=True, null=True),
        ),
    ]
