# Generated by Django 5.2.4 on 2025-07-29 10:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memory_room', '0010_remove_timecapsoulmediafile_cover_image_and_more'),
        ('userauth', '0007_newslettersubscriber'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timecapsoulmediafile',
            name='is_cover_image',
        ),
        migrations.RemoveField(
            model_name='timecapsoulmediafile',
            name='thumbnail_key',
        ),
        migrations.RemoveField(
            model_name='timecapsoulmediafile',
            name='thumbnail_url',
        ),
        migrations.AddField(
            model_name='timecapsoulmediafile',
            name='thumbnail',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='userauth.assets'),
        ),
    ]
