# Generated by Django 5.2.4 on 2025-09-22 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memory_room', '0010_timecapsoulrecipient_is_capsoul_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='memoryroom',
            name='occupied_storage',
            field=models.CharField(blank=True, help_text='Storage used memory-room', max_length=255, null=True),
        ),
    ]
