# Generated by Django 5.2.4 on 2025-09-25 10:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memory_room', '0011_memoryroom_occupied_storage'),
    ]

    operations = [
        migrations.AddField(
            model_name='memoryroom',
            name='room_duplicate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='room_duplicates', to='memory_room.memoryroom', verbose_name='Room Duplicate'),
        ),
    ]
