# Generated by Django 5.2.4 on 2025-07-29 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memory_room', '0011_remove_timecapsoulmediafile_is_cover_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='timecapsoulmediafile',
            name='s3_key',
            field=models.CharField(blank=True, null=True),
        ),
    ]
