# Generated by Django 5.2.4 on 2025-07-29 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memory_room', '0012_timecapsoulmediafile_s3_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='timecapsoulmediafile',
            name='is_cover_image',
            field=models.BooleanField(default=False),
        ),
    ]
