# Generated by Django 5.2.4 on 2025-09-25 10:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memory_room', '0012_memoryroom_room_duplicate'),
    ]

    operations = [
        migrations.AddField(
            model_name='memoryroommediafile',
            name='media_file_duplicate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='media_files_duplicate', to='memory_room.memoryroommediafile', verbose_name='Room Duplicate'),
        ),
    ]
