# Generated by Django 5.2.4 on 2025-09-25 13:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memory_room', '0013_memoryroommediafile_media_file_duplicate'),
    ]

    operations = [
        migrations.AddField(
            model_name='timecapsoul',
            name='room_duplicate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='capsoul_duplicates', to='memory_room.timecapsoul', verbose_name='Time Capsoul Duplicate'),
        ),
    ]
