# Generated by Django 5.2.4 on 2025-07-31 10:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memory_room', '0013_timecapsoulmediafile_is_cover_image'),
        ('userauth', '0007_newslettersubscriber'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='timecapsoulmediafile',
            options={'ordering': ['-created_at'], 'verbose_name': 'TimeCapSoul Media File', 'verbose_name_plural': 'TimeCapSoul Media Files'},
        ),
        migrations.AddField(
            model_name='timecapsouldetail',
            name='is_locked',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='timecapsoulmediafile',
            name='file',
            field=models.FileField(upload_to='media_files/', verbose_name='Media File'),
        ),
        migrations.AlterField(
            model_name='timecapsoulmediafile',
            name='file_size',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='File Size'),
        ),
        migrations.AlterField(
            model_name='timecapsoulmediafile',
            name='is_cover_image',
            field=models.BooleanField(default=False, help_text='Mark if this media is the cover image'),
        ),
        migrations.AlterField(
            model_name='timecapsoulmediafile',
            name='s3_key',
            field=models.CharField(blank=True, max_length=512, null=True, verbose_name='S3 Key'),
        ),
        migrations.AlterField(
            model_name='timecapsoulmediafile',
            name='s3_url',
            field=models.URLField(blank=True, null=True, verbose_name='S3 URL'),
        ),
        migrations.AlterField(
            model_name='timecapsoulmediafile',
            name='thumbnail',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='time_capsoul_media_thumbnails', to='userauth.assets', verbose_name='Thumbnail'),
        ),
        migrations.AlterField(
            model_name='timecapsoulmediafile',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='timecapsoulmediafile',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='time_capsoul_media_files', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='TimeCapSoulMediaFileReplica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Is Deleted')),
                ('file', models.FileField(upload_to='media_files/', verbose_name='Media File')),
                ('file_type', models.CharField(choices=[('image', 'Image'), ('video', 'Video'), ('audio', 'Audio'), ('document', 'Document'), ('other', 'Other')], default='other', max_length=20, verbose_name='File Type')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('file_size', models.BigIntegerField(blank=True, null=True, verbose_name='File Size')),
                ('s3_url', models.URLField(blank=True, null=True, verbose_name='S3 URL')),
                ('s3_key', models.CharField(blank=True, max_length=512, null=True, verbose_name='S3 Key')),
                ('is_cover_image', models.BooleanField(default=False, help_text='Mark if this media is the cover image')),
                ('parent_media_file', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='replica', to='memory_room.timecapsoulmediafile')),
                ('thumbnail', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='timecapsoul_media_file_replicas_thumbnails', to='userauth.assets', verbose_name='Thumbnail')),
                ('time_capsoul', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='media_file_replicas', to='memory_room.timecapsoul')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='timecapsoul_media_file_replicas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'TimeCapSoul Media File Replica',
                'verbose_name_plural': 'TimeCapSoul Media File Replicas',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TimeCapSoulReplica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Is Deleted')),
                ('status', models.CharField(choices=[('sealed', 'Sealed With Love'), ('unlocked', 'Unlocked'), ('created', 'Being Crafted')], default='created')),
                ('capsoul_template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='timecapsouls_replica', to='memory_room.customtimecapsoultemplate', verbose_name='CapSoul Template')),
                ('parent_time_capsoul', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_capsoul_replica', to='memory_room.timecapsoul')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timecapsouls_replica', to=settings.AUTH_USER_MODEL, verbose_name='Owner')),
            ],
            options={
                'verbose_name': 'TimeCapSoul Replica',
                'verbose_name_plural': 'TimeCapSouls Replica',
            },
        ),
    ]
