# Generated by Django 5.2.4 on 2025-09-25 13:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memory_room', '0014_timecapsoul_room_duplicate'),
    ]

    operations = [
        migrations.AddField(
            model_name='timecapsoulmediafile',
            name='media_duplicate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='media_file_duplicates', to='memory_room.timecapsoulmediafile', verbose_name='Room Duplicate'),
        ),
    ]
