# Generated by Django 5.2.4 on 2025-07-31 12:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memory_room', '0014_alter_timecapsoulmediafile_options_and_more'),
        ('userauth', '0007_newslettersubscriber'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='timecapsoulreplica',
            options={},
        ),
        migrations.RemoveField(
            model_name='timecapsoulreplica',
            name='capsoul_template',
        ),
        migrations.AddField(
            model_name='timecapsoulreplica',
            name='cover_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='timecapsoul_replica', to='userauth.assets', verbose_name='Cover Image'),
        ),
        migrations.AddField(
            model_name='timecapsoulreplica',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='TimeCapSoul Name'),
        ),
        migrations.AddField(
            model_name='timecapsoulreplica',
            name='slug',
            field=models.SlugField(blank=True, null=True, verbose_name='Slug'),
        ),
        migrations.AddField(
            model_name='timecapsoulreplica',
            name='summary',
            field=models.TextField(blank=True, null=True, verbose_name='TimeCapSoul Summary'),
        ),
        migrations.AlterField(
            model_name='timecapsoulreplica',
            name='parent_time_capsoul',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='time_capsoul_replica', to='memory_room.timecapsoul'),
        ),
        migrations.AlterField(
            model_name='timecapsoulreplica',
            name='status',
            field=models.CharField(blank=True, choices=[('sealed', 'Sealed With Love'), ('unlocked', 'Unlocked'), ('created', 'Being Crafted')], null=True),
        ),
        migrations.AlterField(
            model_name='timecapsoulreplica',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='time_capsoul_replica', to=settings.AUTH_USER_MODEL, verbose_name='Owner'),
        ),
    ]
