# Generated by Django 5.2.4 on 2025-07-31 13:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memory_room', '0015_alter_timecapsoulreplica_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timecapsoulreplica',
            name='parent_time_capsoul',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='time_capsoul_replica', to='memory_room.timecapsoul'),
        ),
    ]
