# Generated by Django 5.2.4 on 2025-09-30 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memory_room', '0015_timecapsoulmediafile_media_duplicate'),
    ]

    operations = [
        migrations.AddField(
            model_name='timecapsoul',
            name='is_locked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='timecapsoul',
            name='occupied_storage',
            field=models.CharField(blank=True, help_text='Storage used timecap-soul', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='timecapsoul',
            name='unlock_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Unlock Date'),
        ),
    ]
