# Generated by Django 5.2.4 on 2025-07-31 17:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memory_room', '0016_alter_timecapsoulreplica_parent_time_capsoul'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipientsdetail',
            name='time_capsoul',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='recipient_details', to='memory_room.timecapsoul', verbose_name='TimeCapSoul'),
        ),
    ]
