# Generated by Django 5.2.4 on 2025-10-08 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memory_room', '0016_timecapsoul_is_locked_timecapsoul_occupied_storage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='timecapsoulrecipient',
            name='parent_media_refrences',
            field=models.CharField(blank=True, help_text='Comma separated media refrences', max_length=100, null=True),
        ),
    ]
