# Generated by Django 5.2.4 on 2025-10-16 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memory_room', '0017_timecapsoulrecipient_parent_media_refrences'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timecapsoulrecipient',
            name='parent_media_refrences',
            field=models.CharField(blank=True, help_text='Comma separated media refrences', max_length=255, null=True),
        ),
    ]
