# Generated by Django 5.2.4 on 2025-08-06 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memory_room', '0017_alter_recipientsdetail_time_capsoul'),
    ]

    operations = [
        migrations.AddField(
            model_name='memoryroommediafile',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='memoryroommediafile',
            name='file_type',
            field=models.CharField(choices=[('image', 'Image'), ('video', 'Video'), ('audio', 'Audio'), ('other', 'Other')], default='other', max_length=20, verbose_name='File Type'),
        ),
        migrations.AlterField(
            model_name='timecapsoulmediafile',
            name='file_type',
            field=models.CharField(choices=[('image', 'Image'), ('video', 'Video'), ('audio', 'Audio'), ('other', 'Other')], default='other', max_length=20, verbose_name='File Type'),
        ),
        migrations.AlterField(
            model_name='timecapsoulmediafilereplica',
            name='file_type',
            field=models.CharField(choices=[('image', 'Image'), ('video', 'Video'), ('audio', 'Audio'), ('other', 'Other')], default='other', max_length=20, verbose_name='File Type'),
        ),
    ]
