# Generated by Django 5.2.4 on 2025-10-16 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memory_room', '0018_alter_timecapsoulrecipient_parent_media_refrences'),
    ]

    operations = [
        migrations.AddField(
            model_name='timecapsoulmediafile',
            name='preview_or_thumbnail_s3_key',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='timecapsoulmediafilereplica',
            name='preview_or_thumbnail_s3_key',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
