# Generated by Django 5.2.4 on 2025-10-23 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memory_room', '0019_timecapsoulmediafile_preview_or_thumbnail_s3_key_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timecapsoulrecipient',
            name='parent_media_refrences',
            field=models.TextField(blank=True, help_text='Comma separated media refrences', max_length=255, null=True),
        ),
    ]
