# Generated by Django 5.2.4 on 2025-10-24 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memory_room', '0020_alter_timecapsoulrecipient_parent_media_refrences'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memoryroommediafile',
            name='s3_key',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='timecapsoulmediafile',
            name='s3_key',
            field=models.TextField(blank=True, null=True, verbose_name='S3 Key'),
        ),
        migrations.AlterField(
            model_name='timecapsoulmediafilereplica',
            name='s3_key',
            field=models.TextField(blank=True, null=True, verbose_name='S3 Key'),
        ),
    ]
