# Generated by Django 5.2.4 on 2025-11-20 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memory_room', '0021_alter_memoryroommediafile_s3_key_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='memoryroommediafile',
            name='media_type',
            field=models.CharField(choices=[('original', 'Original'), ('duplicate', 'Duplicate'), ('replica', 'Replica')], default='original', max_length=20, verbose_name=' Type'),
        ),
        migrations.AddField(
            model_name='timecapsoulmediafile',
            name='media_type',
            field=models.CharField(choices=[('original', 'Original'), ('duplicate', 'Duplicate'), ('replica', 'Replica')], default='original', max_length=20, verbose_name=' Type'),
        ),
        migrations.AddField(
            model_name='timecapsoulmediafilereplica',
            name='media_type',
            field=models.CharField(choices=[('original', 'Original'), ('duplicate', 'Duplicate'), ('replica', 'Replica')], default='original', max_length=20, verbose_name=' Type'),
        ),
    ]
