# Generated by Django 5.2.4 on 2025-08-19 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='s3_storage_id',
            field=models.UUIDField(blank=True, default=None, null=True),
        ),
    ]
