# Generated by Django 5.2.4 on 2025-07-16 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0002_alter_user_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='assets',
            name='s3_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
