# Generated by Django 5.2.4 on 2025-07-19 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0003_assets_s3_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='assets',
            name='s3_key',
            field=models.CharField(blank=True, null=True),
        ),
    ]
