# Generated by Django 5.2.4 on 2025-07-21 08:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0004_assets_s3_key'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assets',
            old_name='is_created',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='contactus',
            old_name='is_created',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='is_created',
            new_name='created_at',
        ),
    ]
