# Generated by Django 5.2.4 on 2025-07-24 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0005_rename_is_created_assets_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assets',
            name='image',
            field=models.FileField(upload_to='assets/', verbose_name='Assets File'),
        ),
    ]
