# Generated by Django 5.2.4 on 2026-01-06 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0006_session_city_session_country_session_latitude_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assets',
            name='s3_url',
            field=models.URLField(blank=True, max_length=2048, null=True),
        ),
    ]
