# Generated by Django 5.2.4 on 2025-08-01 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0008_user_gender_useraddress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraddress',
            name='postal_code',
            field=models.CharField(max_length=20, verbose_name='Postal Code'),
        ),
    ]
